spring:
  profiles:
    active: local

  datasource:
    url: jdbc:mysql://localhost:3306/fapl
    username: will
    password: '0000'
    driver-class-name: com.mysql.cj.jdbc.Driver

  flyway:
    enabled: true
    baseline-on-migrate: true

  jpa:
    generate-ddl: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
    hibernate:
      ddl-auto: validate

