spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fapl
    username: fapl
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  flyway:
    enabled: true
    baseline-on-migrate: true

  data:
    redis:
      host: localhost
      port: 6379
      password: test

jwt:
  issuer: local
  secret-key: twk4jbz8a6smC4u0Xv6KvQUImMfVZ16/SCR0uKJIv3g=
  access-token:
    expire-length: 3600000
  refresh-token:
    expire-length: 3600000

