name: Deploy to Development Server

env:
  S3_BUCKET_NAME: fapl-project
  AWS_REGION: ap-northeast-2
  CODEDEPLOY_NAME: fapl-dev
  CODEDEPLOY_GROUP: fapl-dev-group
  FAPL_DEV_BUILD_ZIP: fapl-dev-build.zip

#on:
#  pull_request:
#    branches:
#      - develop
#    types:
#      - closed

on:
  workflow_dispatch:
    inputs:
      branch:
        description: '22-cicd'
        required: true

jobs:
  deploy:
#    if: ${{ (github.event.pull_request.merged == true) }}
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          token: ${{secrets.GIT_TOKEN}}
          submodules: true

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Gradle Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Make zip file
        run: |
          mkdir deploy
          cp ./appspec.yml ./deploy/
          cp ./Dockerfile-dev ./deploy/Dockerfile
          cp ./scripts/*.sh ./deploy/
          cp ./build/libs/*.jar ./deploy/
          zip -r -qq -j ./$FAPL_DEV_BUILD_ZIP ./deploy

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Upload to S3
        run: |
          aws s3 cp \
            --region $AWS_REGION \
            ./$FAPL_DEV_BUILD_ZIP s3://$S3_BUCKET_NAME/deploy/

      - name: Code Deploy
        run: aws deploy create-deployment --application-name fapl-dev
          --deployment-config-name CodeDeployDefault.OneAtATime
          --deployment-group-name fapl-dev-group
          --s3-location bucket=$S3_BUCKET_NAME,bundleType=zip,key=deploy/$FAPL_DEV_BUILD_ZIP
